"""
JOB HUNTER BELGIUM
ADECCO BELGIUM - PUBLIC JSON COLLECTOR V1.0

Contract observed from the normal Adecco Belgium job-search page on 2026-09-03:
- POST https://www.adecco.com/api/data/jobs/summarized
- GET  https://www.adecco.com/api/data/jobs/job-description-details/<jobId>/adecco/be/fr-BE/job-details
- keyword search: queryString contains &q=<term>&sort=score desc
- pagination: range=0,10,20,... with 10 jobs per response

This collector does NOT use Playwright and does NOT bypass anti-bot protections.
It uses only the public JSON requests generated by the normal Adecco page.

Historical source key ADECCO is preserved.
"""

from __future__ import annotations

import re
import time
import unicodedata
from datetime import datetime, timezone
from urllib.parse import quote

import requests
from bs4 import BeautifulSoup

from database.models import JobOffer
from sources.batch4_engine import publish_metrics
from sources.mega65_staffing import (
    GENERIC_PRODUCTION,
    SCIENCE_CONTEXT,
    TITLE_EXCLUDE,
    hard_dutch,
    track_hits,
    years_required,
)

ADECCO_API_VERSION = "1.0"
SOURCE_KEY = "ADECCO"
COMPANY = "Adecco Belgium"

BASE = "https://www.adecco.com"
SEARCH_PAGE = f"{BASE}/fr-be/offres-emploi"
SEARCH_API = f"{BASE}/api/data/jobs/summarized"
DETAIL_API_PREFIX = f"{BASE}/api/data/jobs/job-description-details"

TIMEOUT = 30
PAGE_SIZE = 10
MAX_RESULTS_PER_QUERY = 100
REQUEST_DELAY_SECONDS = 0.03
DETAIL_DELAY_SECONDS = 0.04

# High-yield source-specific bank. This is intentionally smaller than the
# global JobHunter bank: Adecco's API is queried by relevance and all results
# are de-duplicated by jobId before any detail call.
KEYWORDS = (
    # Lab / chemistry
    "laborantin",
    "laboratoire",
    "lab analyst",
    "lab technician",
    "technicien laboratoire",
    "analyste laboratoire",
    "chimie",
    "hplc",
    "microbiologie",
    "validation",
    "gmp",
    "lims",
    # Quality / pharma
    "quality",
    "contrôle qualité",
    "qc",
    "qa",
    "pharma",
    "salle blanche",
    # Data / BI
    "data analyst",
    "business analyst",
    "power bi",
    "data quality",
    "master data",
    "reporting",
)

FILTERS_TO_DISPLAY = (
    "{EABD9760-83C3-4DE8-8FB8-FBDA97BF9E2C}|"
    "{D9E4F39D-0721-457A-B218-6F7E22EA31CE}|"
    "{B94A5337-0101-47BC-87DA-CA822CF8596B}|"
    "{56225D45-C806-4C7F-85B0-E406EC3BB82D}|"
    "{817A0693-E6E7-419A-A98B-66D6953791B8}|"
    "{524BE56B-0289-4DE9-BEC0-F64B7F3912B9}|"
    "{5390CDEA-8A62-47AF-82D4-F151DD84BF7F}"
)

BASE_FACETS = (
    "&facet.pivot=IsRemote"
    "&facet.range=Salary_Facet_Yearly"
    "&f.Salary_Facet_Yearly.facet.range.start=0"
    "&f.Salary_Facet_Yearly.facet.range.end=10000"
    "&f.Salary_Facet_Yearly.facet.range.gap=500"
    "&facet.range=Salary_Facet_Hourly"
    "&f.Salary_Facet_Hourly.facet.range.start=0"
    "&f.Salary_Facet_Hourly.facet.range.end=850"
    "&f.Salary_Facet_Hourly.facet.range.gap=5"
)

TITLE_NL_MANDATORY = re.compile(
    r"\b(?:fr\s*[/\-]?\s*nl|nl\s*[/\-]?\s*fr)(?:\s*[/\-]?\s*en)?\b",
    re.I,
)

SESSION = requests.Session()
SESSION.headers.update(
    {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152 Safari/537.36"
        ),
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "fr-BE,fr;q=0.9,en;q=0.8,nl;q=0.3",
        "Referer": SEARCH_PAGE,
    }
)


def clean(value) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def html_text(value) -> str:
    if not value:
        return ""
    return clean(BeautifulSoup(str(value), "html.parser").get_text(" ", strip=True))


def slugify(value: str) -> str:
    text = unicodedata.normalize("NFKD", clean(value))
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text[:140] or "offre"


def public_job_url(summary: dict) -> str:
    title = clean(summary.get("jobTitle"))
    job_id = clean(summary.get("jobId"))
    return f"{SEARCH_PAGE}/{slugify(title)}/{quote(job_id, safe='-')}"


def _search_payload(keyword: str | None, range_value: int) -> dict:
    if keyword:
        query_string = f"&q={keyword}&sort=score desc{BASE_FACETS}"
    else:
        query_string = f"&sort=PostedDate desc{BASE_FACETS}"

    return {
        "queryString": query_string,
        "filtersToDisplay": FILTERS_TO_DISPLAY,
        "range": int(range_value),
        "siteName": "adecco",
        "brand": "adecco",
        "countryCode": "be",
        "languageCode": "fr-BE",
    }


def _post_search(keyword: str | None, range_value: int) -> dict:
    response = SESSION.post(
        SEARCH_API,
        json=_search_payload(keyword, range_value),
        timeout=TIMEOUT,
    )
    response.raise_for_status()
    payload = response.json()
    return payload if isinstance(payload, dict) else {}


def catalog_total() -> int | None:
    """One baseline request gives Adecco's announced open-catalog total."""
    try:
        payload = _post_search(None, 0)
    except Exception:
        return None

    pagination = payload.get("pagination") or {}
    try:
        return int(pagination.get("total"))
    except Exception:
        return None


def search_keyword(keyword: str) -> tuple[list[dict], dict]:
    rows = []
    range_value = 0
    requests_count = 0
    announced_total = None
    errors = 0

    while range_value < MAX_RESULTS_PER_QUERY:
        try:
            payload = _post_search(keyword, range_value)
        except Exception:
            errors += 1
            break

        requests_count += 1

        page_rows = payload.get("jobs") or []
        if not isinstance(page_rows, list):
            page_rows = []

        rows.extend(row for row in page_rows if isinstance(row, dict))

        pagination = payload.get("pagination") or {}
        try:
            announced_total = int(pagination.get("total") or 0)
        except Exception:
            announced_total = None

        if not page_rows:
            break

        if announced_total is not None and range_value + len(page_rows) >= announced_total:
            break

        next_range = pagination.get("nextRange")
        try:
            next_range = int(next_range)
        except Exception:
            next_range = range_value + PAGE_SIZE

        if next_range <= range_value:
            next_range = range_value + PAGE_SIZE

        range_value = next_range

        if REQUEST_DELAY_SECONDS:
            time.sleep(REQUEST_DELAY_SECONDS)

    return rows, {
        "keyword": keyword,
        "requests": requests_count,
        "rows": len(rows),
        "announced_total": announced_total,
        "errors": errors,
    }


def _summary_blob(row: dict) -> str:
    return " | ".join(
        clean(row.get(key))
        for key in (
            "jobTitle",
            "jobCategoryTitle",
            "jobSubCategoryTitle",
            "industryTypeTitle",
            "practiceTitle",
        )
        if clean(row.get(key))
    )


def summary_tracks(row: dict) -> list[str]:
    title = clean(row.get("jobTitle"))
    tracks = track_hits(title)

    if not tracks and GENERIC_PRODUCTION.search(title):
        if SCIENCE_CONTEXT.search(_summary_blob(row)):
            tracks = ["CHEM_LAB"]

    return tracks


def _is_belgium(row: dict) -> bool:
    country = clean(row.get("countryId")).upper()
    if country:
        return country in {"BEL", "BE"}

    # Defensive fallback for future API changes.
    location = clean(row.get("jobLocation"))
    return bool(
        re.search(
            r"\b(?:Belgium|Belgique|Bruxelles|Brussels|Li[eè]ge|Hainaut|Namur|"
            r"Brabant|Antwerpen|Oost-Vlaanderen|West-Vlaanderen|Limburg)\b",
            location,
            re.I,
        )
    )


def _detail(job_id: str) -> dict:
    url = (
        f"{DETAIL_API_PREFIX}/{quote(clean(job_id), safe='-')}/"
        "adecco/be/fr-BE/job-details"
    )
    response = SESSION.get(url, timeout=TIMEOUT)

    if response.status_code in {404, 410}:
        return {"closed": True, "_url": url}

    response.raise_for_status()
    payload = response.json()
    if not isinstance(payload, dict):
        payload = {}

    payload["_url"] = url
    payload["closed"] = (
        clean(payload.get("jobStatusId")).upper() not in {"", "OPEN"}
    )
    return payload


def _detail_description(detail: dict) -> str:
    parts = [
        html_text(detail.get("jobDescription")),
        html_text(detail.get("clientJobDescription")),
        html_text(detail.get("clientDescription")),
    ]
    return clean(" ".join(part for part in parts if part))


def _fit(summary: dict, detail: dict, tracks: list[str]) -> tuple[str, int | None]:
    title = clean(detail.get("jobName") or summary.get("jobTitle"))
    description = _detail_description(detail)
    years = years_required(description)

    if not tracks:
        return "NOT_TARGET", years
    if TITLE_EXCLUDE.search(title):
        return "REJECT_SENIORITY", years
    if not _is_belgium(summary):
        return "REJECT_GEO", years
    if TITLE_NL_MANDATORY.search(title) or hard_dutch(description):
        return "REJECT_DUTCH", years
    if years is not None and years >= 4:
        return "REJECT_EXPERIENCE", years
    if years == 3:
        return "STRETCH", years
    return "GOOD", years


def _make_job(summary: dict, detail: dict) -> JobOffer:
    title = clean(detail.get("jobName") or summary.get("jobTitle"))
    location = clean(detail.get("location") or summary.get("jobLocation")) or "Belgium"
    description = _detail_description(detail)
    job_id = clean(detail.get("jobId") or summary.get("jobId"))
    published = clean(
        detail.get("postedDate")
        or detail.get("firstPostedDate")
        or summary.get("postedDate")
    ) or None
    contract = clean(
        detail.get("contractTypeTitle")
        or detail.get("contract")
        or summary.get("contractTypeTitle")
    ) or None

    region_lang = clean(
        detail.get("publishedRegionCodeId")
        or summary.get("publishedRegionCodeId")
    ).lower()
    language = None
    if region_lang.startswith("fr"):
        language = "fr"
    elif region_lang.startswith("nl"):
        language = "nl"
    elif region_lang.startswith("en"):
        language = "en"

    job = JobOffer(
        source=SOURCE_KEY,
        external_id=job_id,
        title=title,
        company=COMPANY,
        location=location,
        description=description,
        url=public_job_url(summary),
        date_published=published,
        contract_type=contract,
        language=language,
    )

    job.collection_channel = SOURCE_KEY
    job.origin_source = SOURCE_KEY
    job.adecco_json_api = True
    job.apply_url = clean(detail.get("applyUri") or summary.get("applyUri"))
    job.adecco_category = clean(
        detail.get("jobCategoryTitle") or summary.get("jobCategoryTitle")
    )
    job.adecco_subcategory = clean(
        detail.get("jobSubCategoryTitle") or summary.get("jobSubCategoryTitle")
    )
    return job


def _dedupe_jobs(jobs: list[JobOffer]) -> list[JobOffer]:
    out = []
    seen = set()
    for job in jobs:
        key = (
            clean(getattr(job, "external_id", "")),
            clean(getattr(job, "title", "")).lower(),
            clean(getattr(job, "location", "")).lower(),
        )
        if key in seen:
            continue
        seen.add(key)
        out.append(job)
    return out


def collect_adecco_jobs() -> list[JobOffer]:
    print("ADECCO - collecte JSON publique ciblée (sans navigateur)")

    announced_catalog_total = catalog_total()
    if announced_catalog_total is not None:
        print("ADECCO - catalogue annoncé :", announced_catalog_total)

    all_rows = {}
    total_summary_rows = 0
    summary_requests = 1 if announced_catalog_total is not None else 0
    query_errors = 0
    query_stats = []

    for index, keyword in enumerate(KEYWORDS, 1):
        rows, stats = search_keyword(keyword)
        query_stats.append(stats)
        summary_requests += int(stats["requests"])
        query_errors += int(stats["errors"])
        total_summary_rows += len(rows)

        for row in rows:
            job_id = clean(row.get("jobId"))
            if not job_id:
                continue
            all_rows[job_id] = row

        print(
            f"[{index:02d}/{len(KEYWORDS):02d}] {keyword:<24} | "
            f"rows={len(rows):3d} | unique_total={len(all_rows):3d} | "
            f"announced={stats.get('announced_total')}"
        )

    query_duplicates = max(0, total_summary_rows - len(all_rows))

    target_summaries = []
    non_target = 0
    rejected_geo = 0

    for job_id, summary in all_rows.items():
        tracks = summary_tracks(summary)
        if not tracks:
            non_target += 1
            continue

        if not _is_belgium(summary):
            rejected_geo += 1
            continue

        target_summaries.append((job_id, summary, tracks))

    jobs = []
    candidates = len(target_summaries)
    detail_probed = 0
    detail_errors = 0
    closed = 0
    rejected_language = 0
    rejected_seniority = 0
    rejected_experience = 0
    stretch = 0

    for index, (job_id, summary, tracks) in enumerate(target_summaries, 1):
        try:
            detail = _detail(job_id)
        except Exception as exc:
            detail_errors += 1
            print(
                f"  [{index:02d}/{len(target_summaries):02d}] "
                f"DETAIL_ERROR | {clean(summary.get('jobTitle'))} | "
                f"{type(exc).__name__}: {exc}"
            )
            continue

        detail_probed += 1

        if detail.get("closed"):
            closed += 1
            continue

        fit, years = _fit(summary, detail, tracks)

        if fit == "REJECT_GEO":
            rejected_geo += 1
            continue
        if fit == "REJECT_DUTCH":
            rejected_language += 1
            continue
        if fit == "REJECT_SENIORITY":
            rejected_seniority += 1
            continue
        if fit == "REJECT_EXPERIENCE":
            rejected_experience += 1
            continue
        if fit == "NOT_TARGET":
            non_target += 1
            continue
        if fit not in {"GOOD", "STRETCH"}:
            continue

        if fit == "STRETCH":
            stretch += 1

        job = _make_job(summary, detail)
        jobs.append(job)

        print(
            f"  KEEP | {fit:<7} | {job.title} | {job.location} | "
            f"years={years}"
        )

        if DETAIL_DELAY_SECONDS:
            time.sleep(DETAIL_DELAY_SECONDS)

    before_dedupe = len(jobs)
    jobs = _dedupe_jobs(jobs)
    output_duplicates = before_dedupe - len(jobs)

    metrics = {
        "catalog_total": announced_catalog_total,
        "keyword_queries": len(KEYWORDS),
        "summary_requests": summary_requests,
        "summary_rows": total_summary_rows,
        "seen": len(all_rows),
        "query_duplicates": query_duplicates,
        "candidates": candidates,
        "detail_probed": detail_probed,
        "kept": len(jobs),
        "non_target": non_target,
        "rejected_language": rejected_language,
        "rejected_geo": rejected_geo,
        "rejected_seniority": rejected_seniority,
        "rejected_experience": rejected_experience,
        "stretch": stretch,
        "closed": closed,
        "detail_errors": detail_errors,
        "query_errors": query_errors,
        "duplicates_removed": output_duplicates,
    }

    publish_metrics(SOURCE_KEY, metrics)

    print()
    print("=" * 96)
    print("ADECCO - JSON COLLECTOR V1.0")
    print("=" * 96)
    for key, value in metrics.items():
        print(f"{key:<28}: {value}")

    for job in jobs:
        print("KEEP |", job.title, "|", job.location, "|", job.url)

    return jobs


def regression_checks() -> dict:
    fake_lab = {
        "jobTitle": "Technicien de laboratoire",
        "jobCategoryTitle": "Chimie",
        "countryId": "BEL",
    }
    fake_quality = {
        "jobTitle": "Contrôleur qualité",
        "jobCategoryTitle": "Assurance qualité",
        "countryId": "BEL",
    }
    fake_pharma_prod = {
        "jobTitle": "Opérateur de production | Pharma",
        "jobCategoryTitle": "Ouvriers/ères polyvalent(e)s",
        "industryTypeTitle": "Industrial",
        "countryId": "BEL",
    }
    fake_foreign = {
        "jobTitle": "Data Analyst",
        "countryId": "NLD",
    }

    return {
        "lab_title_target": "CHEM_LAB" in summary_tracks(fake_lab),
        "quality_title_target": "CHEM_LAB" in summary_tracks(fake_quality),
        "pharma_production_target": "CHEM_LAB" in summary_tracks(fake_pharma_prod),
        "data_title_target": "DATA_BI" in summary_tracks(
            {"jobTitle": "Business / Financial Data Analyst", "countryId": "BEL"}
        ),
        "foreign_rejected": not _is_belgium(fake_foreign),
        "frnl_title_rejected": bool(
            TITLE_NL_MANDATORY.search("Opérateur qualité FRNL")
        ),
        "keyword_contract": (
            _search_payload("data analyst", 0)["queryString"].startswith(
                "&q=data analyst&sort=score desc"
            )
        ),
        "range_contract": _search_payload("quality", 30)["range"] == 30,
        "public_url_contains_jobid": (
            "730-1069-2" in public_job_url(
                {"jobTitle": "Technicien de laboratoire", "jobId": "730-1069-2"}
            )
        ),
    }




# JOBHUNTER_UNIFIED_DISCOVERY_DETAIL_V1
from sources.unified_discovery import get_source_query_terms
_UD_ADECCO_CORE_TERMS = list(KEYWORDS)
KEYWORDS = tuple(
    get_source_query_terms(
        "ADECCO",
        _UD_ADECCO_CORE_TERMS,
        rotation_buckets=4,
    )
)

if __name__ == "__main__":
    collect_adecco_jobs()
